### ISSUE TITLE
Create repo for csp_download module. Push it galaxy. Integrate with these playbooks.

### ISSUE THREAD

**Issue by sherl0cks** [rhtconsulting/ansible-middleware-playbooks#24]
And then look to get add to ansible extras.

**Comment by sabre1041** [comment]
@sherl0cks just a heads up that i'm starting to put this task into motion and should have everything in place by eow (6/3)

**Comment by sherl0cks** [comment]
@sabre1041 sweet.

**Comment by sherl0cks** [comment]
Fixed by #27
