### ISSUE TITLE
Use PIP Module Instead of Action Module

### ISSUE THREAD

**Issue by sherl0cks** [rhtconsulting/ansible-middleware-playbooks#7]
https://github.com/rhtconsulting/ansible-middleware-playbooks/blob/master/eap6.4-centos7.yml#L26

**Comment by sherl0cks** [comment]
Perhaps this is just clarification more than anything. Why are you using action module @sabre1041?

**Comment by sabre1041** [comment]
@sherl0cks no reason in particular. I agree, the native module should be used

**Comment by sabre1041** [comment]
Validated this functionality is working
